### ISSUE TITLE
Clock not work (last update)

### ISSUE THREAD

**Issue by xxfabry89xx** [TheWhisp/android_device_samsung_wilcoxltexx#21]
last update 8.10 , the clock does not work , remains firm and does not update automatically , I go back to the penultimate update.

**Comment by flepp4ever** [comment]
I had the same problem and nearly solved it.
After doing a reset, wiping caches and reinstalling the rom the system clock and the widgets are working well, but after a reboot i see that the clock is set wrong for 1-2 seconds before it gets synced. Whatsapp shows an error message at startup because of this that the system date is wrong.
Hope this bug gets fixed soon.

**Comment by xxfabry89xx** [comment]
I've also solved temporarily by simply doing a wipe and a wipe Dalvik cache, but the problem recurs after a while.

**Comment by xxfabry89xx** [comment]
*wipe cache e wipe dalvik

**Comment by TheWhisp** [comment]
I had the same problem 2 or 3 weeks ago, had to factory reset. Not sure why that happened. Hasn't happened since.

**Comment by xxfabry89xx** [comment]
Guys stay away since the last update on 10 October , the problem of the watch is the first in a long line up to get to the system crash . I do not know why I am giving all these problems I hope will solve as soon as possible . I had to format the whole phone and then go back to the old update on 4 October .

**Comment by ashrambo** [comment]
After of install the rom you must delete the file "time_daemon" placed in "system /bin" with rootexplorer or similar and restart the terminal

**Comment by shinra00** [comment]
Hey, i have always performed clean installations of the roms, wipe cache and format system and i started to get this bug. 

This is a really nasty one because the alarm won't fire up, I've got late for work today. 

Any clue how to solve this?

**Comment by TheWhisp** [comment]
When I got that bug it didn't matter on which build I was on. It persisted even after I downgraded. This bug was probably introduced in one of the previous builds and corrupted something in /data. After I wiped data and installed the same build responsible for the bug, it didn't happen. And hasn't happened since.

**Comment by shinra00** [comment]
Will try a to wipe data and will report it, thanks

**Comment by jackfedrik** [comment]
when i turn on the phone the message qulacom.timeservice doesn't work appear...in the last update,
in tre prev update this happens too...and collapse also the dialer process...

**Comment by TheWhisp** [comment]
it works fine for me. I have been using cm-12 since I released the first build...
