### ISSUE TITLE
Home button not working properly.

### ISSUE THREAD

**Issue by justfun23** [TheWhisp/android_device_samsung_wilcoxltexx#29]
Hi. It struck me as rather odd when I locked my phone then kept pressing the home button and nothing happened. As far as I know it should wake up my phone.Also , is there is any way to get double-tap wake up using CM12? Can someone provide some help ? Thanks.

Update: After a thorough search on the wide net , I have found a possible fix proven wrong. Fix was : under System/usr/keylayout edit generic.kl find key 172 home and change it to key 172 home wake. It was proven wrong .

**Comment by megabitus98** [comment]
I have the same problem.

**Comment by cezar57** [comment]
For the first question: i heard that android has removed this feature so that you can no longer unlock the phone with the home button. As far as I know there are some files that have to be rewritten. I will have a look tomorow. As for the second question: the double tap to wake is found mainly on 2 CPU devices due to the fact that the weakest one will work all the time. So on an Express 2 this will totally drain your battery. There are some applications that simulate the double tap to wake but I don't know exactly how they work. I will also have a look at them tomorrow and come back with an answer.

**Comment by justfun23** [comment]
On further retries rewriting some files in system/usr/keylayout I have come towards the problem of my phone acting rather awkward in the way that my power button was not functional at all. The only fix I could find was the reflashing of the rom+gapps. I've seen in some other discussion on XDA that it might be the fault of flashing the gapps in which case, what is to be done ? Thank you in advance.

**Comment by LeonardoSpinale17** [comment]
This happens not only on our Samsung Galaxy Express 2 but also on other devices with CyanogenMod 12 , I tried a ROM CyanogenMod 12 on S3 and the home button does not wake the phone .. = )

**Comment by megabitus98** [comment]
So the problem is from CM 12?

**Comment by LeonardoSpinale17** [comment]
I think so , I think it CyanogeMod 12 not to use the home button to wake the phone

**Comment by justfun23** [comment]
There has to be something to be done, to stabilize the system after modifying the generic.kl file. After you edit it and put key 172 HOME WAKE the power button does not work anymore in any circumstances

**Comment by LeonardoSpinale17** [comment]
I do not know how to help you , to stabilize try to reinstall the system again from scratch :)

**Comment by TheWhisp** [comment]
AOSP doesn't support to wake up phone with home button by default since it is meant to used with on-screen buttons. CM just hadn't added it at the time I released those builds.
