### ISSUE TITLE
Multitasking problem

### ISSUE THREAD

**Issue by MarcoSanna2308** [TheWhisp/android_device_samsung_wilcoxltexx#32]
A volte tenendo premuto il tasto home non avvia il multitasking, anche se inserito nelle impostazioni. Ho l'ultima versione del 21 dicembre 2014 cyanogenmod 12

**Comment by Dige90** [comment]
Marco, riscrivilo in inglese che, non sono tutti italiani. Per il tuo problema, fai di nuovo una nuova installazione anche perchè a me CM12 - 20141221 mi gira molto bene.

Marco, rewrite it in English, are not all Italian. For your problem, do it again. a new installation also because to me CM12-20141221 turns me very well.
